export const DEFAULT_MODEL = "@cf/zai-org/glm-4.7-flash";

export const APP_CONFIG = {
  title: "CF Worker Chat",
  subtitle: "整洁、稳定的多模型 AI 对话。",
  inputHint: "Enter 发送，Shift+Enter 换行。",
  workspaceBadges: [
    { label: "Streaming", tone: "success" },
    { label: "Workers AI", tone: "info" },
    { label: "Multi-model", tone: "neutral" },
  ],
  composerShortcuts: [
    {
      label: "拆解",
      prompt: "请把这个需求拆解成目标、约束、实现步骤和潜在风险。",
    },
    {
      label: "编码",
      prompt: "请基于这个需求给出实现方案、边界条件和可能风险。",
    },
    {
      label: "总结",
      prompt: "请把这段内容总结成要点、结论和行动项。",
    },
    {
      label: "改写",
      prompt: "请在不改变核心意思的前提下，把这段内容改写得更清晰、更自然。",
    },
  ],
  starterPrompts: [
    {
      title: "需求拆解",
      description: "先把目标、约束、步骤和风险拆清楚。",
      prompt: "请把这个需求拆解成目标、约束、实现步骤和潜在风险。",
    },
    {
      title: "代码方案",
      description: "从需求出发拆分实现步骤、边界和风险。",
      prompt: "请基于这个需求给出实现方案、边界条件和可能风险。",
    },
    {
      title: "内容总结",
      description: "快速提炼重点、结论和行动项。",
      prompt: "请把这段内容总结成要点、结论和行动项。",
    },
  ],
  modelPicker: {
    featuredLabel: "常用模型",
    catalogLabel: "更多模型",
    searchPlaceholder: "搜索模型或提供方",
    helperText: "主界面只保留少量常用模型，完整目录可按需要展开。",
  },
};

const MODEL_REGISTRY = [
  {
    id: "@cf/zai-org/glm-4.7-flash",
    label: "GLM-4.7-Flash",
    shortLabel: "GLM 4.7",
    provider: "Zhipu AI",
    family: "GLM",
    description: "默认模型，适合多语言聊天、写作整理与高频日常对话。",
    contextWindow: 131072,
    speedTag: "Fast",
    costTag: "Balanced",
    qualityTag: "Versatile",
    recommendedFor: "多轮对话、写作整理、中文体验",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: true,
    sortOrder: 10,
  },
  {
    id: "@cf/meta/llama-3.1-8b-instruct-fast",
    label: "Llama 3.1 8B Fast",
    shortLabel: "Llama 3.1 8B",
    provider: "Meta",
    family: "Llama 3.1",
    description: "轻量、响应快，适合短对话、草稿和快速试用。",
    contextWindow: 128000,
    speedTag: "Fast",
    costTag: "Lower",
    qualityTag: "Lean",
    recommendedFor: "轻量问答、快速试错、短文本处理",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsReasoning: false,
    enabled: true,
    featured: true,
    sortOrder: 20,
  },
  {
    id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    label: "Llama 3.3 70B Fast",
    shortLabel: "Llama 3.3 70B",
    provider: "Meta",
    family: "Llama 3.3",
    description: "能力更强，适合复杂生成、重写和质量优先的任务。",
    contextWindow: 24000,
    speedTag: "Strong",
    costTag: "Higher",
    qualityTag: "Deep",
    recommendedFor: "复杂生成、质量优先、深度改写",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 30,
  },
  {
    id: "@cf/meta/llama-4-scout-17b-16e-instruct",
    label: "Llama 4 Scout",
    shortLabel: "Llama 4 Scout",
    provider: "Meta",
    family: "Llama 4",
    description: "较新的通用模型，适合更长上下文和更广泛的通用对话任务。",
    contextWindow: 131000,
    speedTag: "Balanced",
    costTag: "Mid",
    qualityTag: "General",
    recommendedFor: "长上下文、日常通用、信息整理",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: false,
    enabled: true,
    featured: true,
    sortOrder: 40,
  },
  {
    id: "@cf/nvidia/nemotron-3-120b-a12b",
    label: "Nemotron 3 120B",
    shortLabel: "Nemotron 120B",
    provider: "NVIDIA",
    family: "Nemotron 3",
    description: "偏向 agent / tool use 的大型模型，适合复杂系统性任务。",
    contextWindow: 32000,
    speedTag: "Agentic",
    costTag: "Higher",
    qualityTag: "Systems",
    recommendedFor: "复杂任务拆解、工具调用、Agent 场景",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 50,
  },
  {
    id: "@cf/moonshotai/kimi-k2.5",
    label: "Kimi K2.5",
    shortLabel: "Kimi K2.5",
    provider: "Moonshot AI",
    family: "Kimi K2.5",
    description: "超长上下文的前沿模型，适合复杂 agent 工作流、工具调用和长文任务。",
    contextWindow: 256000,
    speedTag: "Frontier",
    costTag: "Higher",
    qualityTag: "Agentic",
    recommendedFor: "超长上下文、复杂任务、工具工作流",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: false,
    sortOrder: 55,
  },
  {
    id: "@cf/ibm-granite/granite-4.0-h-micro",
    label: "Granite 4.0 H Micro",
    shortLabel: "Granite 4.0",
    provider: "IBM",
    family: "Granite 4.0",
    description: "轻量但偏工具型的模型，适合 RAG、多代理流程和稳定的任务执行。",
    contextWindow: 131000,
    speedTag: "Efficient",
    costTag: "Lower",
    qualityTag: "Tool-ready",
    recommendedFor: "RAG、边缘部署、轻量 agent 工作流",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 58,
  },
  {
    id: "@cf/openai/gpt-oss-120b",
    label: "GPT-OSS 120B",
    shortLabel: "GPT-OSS 120B",
    provider: "OpenAI",
    family: "GPT-OSS",
    description: "高推理能力模型，适合复杂问题、代码分析与步骤化思考。",
    contextWindow: 128000,
    speedTag: "Reasoning",
    costTag: "Higher",
    qualityTag: "High reasoning",
    recommendedFor: "复杂推理、代码分析、结构化任务",
    taskType: "chat",
    inputMode: "hybrid",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: false,
    sortOrder: 60,
  },
  {
    id: "@cf/openai/gpt-oss-20b",
    label: "GPT-OSS 20B",
    shortLabel: "GPT-OSS 20B",
    provider: "OpenAI",
    family: "GPT-OSS",
    description: "更低延迟的 GPT-OSS 选择，适合想兼顾速度与推理的场景。",
    contextWindow: 128000,
    speedTag: "Fast reasoning",
    costTag: "Balanced",
    qualityTag: "Reasoning-lite",
    recommendedFor: "速度优先的推理、工具草稿、快速分析",
    taskType: "chat",
    inputMode: "hybrid",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: true,
    sortOrder: 70,
  },
  {
    id: "@cf/qwen/qwen3-30b-a3b-fp8",
    label: "Qwen3 30B A3B",
    shortLabel: "Qwen3 30B",
    provider: "Qwen",
    family: "Qwen3",
    description: "兼顾推理、函数调用和多语言，适合工具型与任务型对话。",
    contextWindow: 32768,
    speedTag: "Balanced",
    costTag: "Efficient",
    qualityTag: "Tool-ready",
    recommendedFor: "工具调用、多语言任务、结构化输出",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: true,
    sortOrder: 80,
  },
  {
    id: "@cf/qwen/qwen2.5-coder-32b-instruct",
    label: "Qwen2.5 Coder 32B",
    shortLabel: "Qwen2.5 Coder",
    provider: "Qwen",
    family: "Qwen2.5 Coder",
    description: "偏开发者场景的代码模型，适合生成、重构、调试和技术问答。",
    contextWindow: 32768,
    speedTag: "Code",
    costTag: "Mid",
    qualityTag: "Developer",
    recommendedFor: "代码生成、调试、重构、技术问答",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 85,
  },
  {
    id: "@cf/google/gemma-3-12b-it",
    label: "Gemma 3 12B IT",
    shortLabel: "Gemma 3 12B",
    provider: "Google",
    family: "Gemma 3",
    description: "适合总结、问答和轻量推理，也可作为更简洁的备用模型。",
    contextWindow: 80000,
    speedTag: "Balanced",
    costTag: "Mid",
    qualityTag: "Compact",
    recommendedFor: "总结、问答、轻量推理",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 90,
  },
  {
    id: "@cf/meta/llama-3.2-3b-instruct",
    label: "Llama 3.2 3B",
    shortLabel: "Llama 3.2 3B",
    provider: "Meta",
    family: "Llama 3.2",
    description: "小而快的多语言文本模型，适合轻量聊天、摘要和检索增强场景。",
    contextWindow: 80000,
    speedTag: "Fast",
    costTag: "Lower",
    qualityTag: "Compact",
    recommendedFor: "轻量聊天、摘要、检索增强",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 92,
  },
  {
    id: "@cf/meta/llama-3.2-1b-instruct",
    label: "Llama 3.2 1B",
    shortLabel: "Llama 3.2 1B",
    provider: "Meta",
    family: "Llama 3.2",
    description: "更轻量的文本模型，适合超低成本草稿、短问答和快速试探。",
    contextWindow: 60000,
    speedTag: "Faster",
    costTag: "Lowest",
    qualityTag: "Ultra-light",
    recommendedFor: "短问答、草稿、低成本快速试错",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 94,
  },
  {
    id: "@cf/mistralai/mistral-small-3.1-24b-instruct",
    label: "Mistral Small 3.1 24B",
    shortLabel: "Mistral Small 3.1",
    provider: "MistralAI",
    family: "Mistral Small 3.1",
    description: "支持长上下文与函数调用，适合工具型工作流与较复杂的通用对话。",
    contextWindow: 128000,
    speedTag: "Balanced",
    costTag: "Mid",
    qualityTag: "Tool-ready",
    recommendedFor: "长上下文、函数调用、通用任务",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: false,
    enabled: true,
    featured: false,
    sortOrder: 100,
  },
  {
    id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    label: "DeepSeek R1 Distill Qwen 32B",
    shortLabel: "DeepSeek R1 32B",
    provider: "DeepSeek",
    family: "DeepSeek R1 Distill",
    description: "高推理能力模型，适合复杂分析、步骤化思考和高难度问答。",
    contextWindow: 80000,
    speedTag: "Reasoning",
    costTag: "Higher",
    qualityTag: "Deep reasoning",
    recommendedFor: "复杂推理、分析、难题求解",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: false,
    sortOrder: 110,
  },
  {
    id: "@cf/qwen/qwq-32b",
    label: "QwQ 32B",
    shortLabel: "QwQ 32B",
    provider: "Qwen",
    family: "QwQ",
    description: "Qwen 系列推理模型，适合更强思考链路、复杂任务与工具调用。",
    contextWindow: 24000,
    speedTag: "Reasoning",
    costTag: "Mid",
    qualityTag: "Reasoning-first",
    recommendedFor: "复杂推理、工具调用、较难问题",
    taskType: "chat",
    inputMode: "messages",
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsReasoning: true,
    enabled: true,
    featured: false,
    sortOrder: 120,
  },
];

function sortModels(models) {
  return [...models].sort((left, right) => {
    if (left.sortOrder !== right.sortOrder) {
      return left.sortOrder - right.sortOrder;
    }

    return left.label.localeCompare(right.label, "en");
  });
}

export function getModelCatalog() {
  return sortModels(MODEL_REGISTRY.filter((model) => model.enabled));
}

export function getEnabledModels() {
  return getModelCatalog();
}

export function getFeaturedModels() {
  return getModelCatalog().filter((model) => model.featured);
}

export function getModelById(modelId) {
  return getModelCatalog().find((model) => model.id === modelId) ?? null;
}

export function isSupportedModel(modelId) {
  return getModelById(modelId) !== null;
}

export function buildClientConfig() {
  const modelCatalog = getModelCatalog();
  const featuredModels = getFeaturedModels();

  return {
    ...APP_CONFIG,
    defaultModel: DEFAULT_MODEL,
    models: modelCatalog,
    featuredModels,
    modelCatalog,
  };
}
